# Generated by Django 3.2.8 on 2021-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
    ]
