# Generated by Django 3.2.8 on 2021-11-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infovaksin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
