# Generated by Django 3.2.8 on 2021-10-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaLokasi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AddLokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaLokasi', models.CharField(max_length=20)),
                ('JenisVaksin', models.CharField(max_length=20)),
                ('RincianDosis', models.CharField(max_length=20)),
                ('Alamat', models.TextField()),
                ('Kritik', models.TextField()),
                ('pulau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LokasiVaksin.pulau')),
            ],
        ),
    ]
