# Generated by Django 3.2.8 on 2021-10-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LokasiVaksin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaVaksin', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='addlokasi',
            name='JenisVaksin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LokasiVaksin.vaksin'),
        ),
    ]
