# Generated by Django 3.2.8 on 2021-10-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LokasiVaksin', '0002_auto_20211029_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlokasi',
            name='Kritik',
        ),
    ]
