# Generated by Django 3.2.8 on 2021-11-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LokasiVaksin', '0003_remove_addlokasi_kritik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaLokasi', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pulau',
            name='provinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LokasiVaksin.provinsi'),
        ),
    ]
