# Generated by Django 3.2.8 on 2021-11-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LokasiVaksin', '0004_auto_20211105_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulau',
            name='provinsi',
        ),
        migrations.AddField(
            model_name='provinsi',
            name='pulau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LokasiVaksin.pulau'),
        ),
    ]
