# Generated by Django 3.2.8 on 2021-11-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LokasiVaksin', '0005_auto_20211105_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlokasi',
            name='provinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LokasiVaksin.provinsi'),
        ),
    ]
