# Generated by Django 3.2.8 on 2021-11-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LokasiVaksin', '0006_addlokasi_provinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlokasi',
            name='provinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LokasiVaksin.provinsi'),
        ),
        migrations.AlterField(
            model_name='addlokasi',
            name='pulau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LokasiVaksin.pulau'),
        ),
    ]
