# Generated by Django 3.2.8 on 2021-11-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LokasiVaksin', '0008_auto_20211105_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlokasi',
            options={'ordering': ['pulau']},
        ),
    ]
